---
title: "Clean Test Data"
author: "Eliza Baier"
output: html_document
date: "2025-03-09"
---

# Load libaries

```{r setup, include=FALSE}
# Load libraries
library(tidyverse)
library(dplyr)
library(ggplot2)
library(randomForest)
library(caret)
library(nnet)
library(rminer)

# Read in application test data
test <- read.csv("application_test.csv")
getwd()
```

## Clean and Update Application Data

```{r}
# Copy train set to new variable
test_clean <- test

# Impute OWN_CAR_BIN NAs with -1
test_clean <- test_clean |>
  mutate(OWN_CAR_AGE = ifelse(is.na(OWN_CAR_AGE), -1, OWN_CAR_AGE))

# Create categorical OWN_CAR_BIN
test_clean$OWN_CAR_BIN <- test_clean$OWN_CAR_AGE |>
        cut(breaks = c(-1, 0, 5, 10, 15, 20, 25, 30, 100), 
        right = FALSE, 
        labels = c("No Car", "0-4 Years Old", "5-9 Years Old", "10-14 Years Old", 
                 "15-19 Years Old", "20-24 Years Old", "25-29 Years Old", "30+ Years Old"))

# Check OWN_CAR_BIN variable
test_clean |>
  count(OWN_CAR_BIN) |>
  mutate(percentage = n / sum(n) * 100) |>
  arrange(desc(n))

# Create binary OWN_ASSET variable
test_clean <- test_clean |>
  mutate(OWN_ASSET = ifelse(FLAG_OWN_REALTY == "Y" | FLAG_OWN_CAR == "Y", 1, 0))

# Check OWN_ASSET variable
train_clean |>
  count(OWN_ASSET) |>
  mutate(percentage = n / sum(n) * 100) |>
  arrange(desc(n))

# Remove irrelevant variables
test_clean <- test_clean |>
  select(-c(COMMONAREA_AVG, COMMONAREA_MODE, COMMONAREA_MEDI, NONLIVINGAPARTMENTS_AVG, NONLIVINGAPARTMENTS_MODE, NONLIVINGAPARTMENTS_MEDI, LIVINGAPARTMENTS_AVG, LIVINGAPARTMENTS_MODE, LIVINGAPARTMENTS_MEDI, FLOORSMIN_AVG, FLOORSMIN_MODE, FLOORSMIN_MEDI, YEARS_BUILD_AVG, YEARS_BUILD_MODE, YEARS_BUILD_MEDI, LANDAREA_AVG, LANDAREA_MODE, LANDAREA_MEDI, BASEMENTAREA_AVG, BASEMENTAREA_MODE, BASEMENTAREA_MEDI, NONLIVINGAREA_AVG, NONLIVINGAREA_MODE, NONLIVINGAREA_MEDI, ELEVATORS_AVG, ELEVATORS_MODE, ELEVATORS_MEDI, APARTMENTS_AVG, APARTMENTS_MODE, APARTMENTS_MEDI, ENTRANCES_AVG, ENTRANCES_MODE, ENTRANCES_MEDI, LIVINGAREA_AVG, LIVINGAREA_MODE, LIVINGAREA_MEDI, CNT_CHILDREN, FLAG_MOBIL, FLAG_EMP_PHONE, FLAG_WORK_PHONE, FLAG_CONT_MOBILE, FLAG_EMAIL, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, LIVE_CITY_NOT_WORK_CITY, YEARS_BEGINEXPLUATATION_AVG, YEARS_BEGINEXPLUATATION_MODE, YEARS_BEGINEXPLUATATION_MEDI, EMERGENCYSTATE_MODE, DEF_30_CNT_SOCIAL_CIRCLE, OBS_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE, DEF_60_CNT_SOCIAL_CIRCLE, FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, FLAG_DOCUMENT_6, FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9, FLAG_DOCUMENT_10, FLAG_DOCUMENT_11, FLAG_DOCUMENT_12, FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15, FLAG_DOCUMENT_16, FLAG_DOCUMENT_17, FLAG_DOCUMENT_18, FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21, AMT_REQ_CREDIT_BUREAU_HOUR, AMT_REQ_CREDIT_BUREAU_DAY, AMT_REQ_CREDIT_BUREAU_WEEK, AMT_REQ_CREDIT_BUREAU_MON, AMT_REQ_CREDIT_BUREAU_QRT, AMT_REQ_CREDIT_BUREAU_YEAR, FLAG_PHONE, FLOORSMAX_AVG, FLOORSMAX_MODE, FLOORSMAX_MEDI, HOUR_APPR_PROCESS_START, REG_CITY_NOT_WORK_CITY, TOTALAREA_MODE, WALLSMATERIAL_MODE, FONDKAPREMONT_MODE, WEEKDAY_APPR_PROCESS_START, REGION_RATING_CLIENT_W_CITY))

# Factor remaining categorical variables
test_clean <- test_clean |>
  mutate(NAME_CONTRACT_TYPE = factor(NAME_CONTRACT_TYPE),
         NAME_TYPE_SUITE = factor(NAME_TYPE_SUITE),
         OCCUPATION_TYPE = factor(OCCUPATION_TYPE),
         CODE_GENDER = factor(CODE_GENDER),
         FLAG_OWN_CAR = factor(FLAG_OWN_CAR),
         FLAG_OWN_REALTY = factor(FLAG_OWN_REALTY),
         NAME_TYPE_SUITE = factor(NAME_TYPE_SUITE),
         NAME_INCOME_TYPE = factor(NAME_INCOME_TYPE),
         NAME_EDUCATION_TYPE = factor(NAME_EDUCATION_TYPE),
         NAME_FAMILY_STATUS = factor(NAME_FAMILY_STATUS),
         NAME_HOUSING_TYPE = factor(NAME_HOUSING_TYPE),
         HOUSETYPE_MODE = factor(HOUSETYPE_MODE),
         OCCUPATION_TYPE = factor(OCCUPATION_TYPE),
         ORGANIZATION_TYPE = factor(ORGANIZATION_TYPE),
         HOUSETYPE_MODE = factor(HOUSETYPE_MODE),
         OWN_ASSET = factor(OWN_ASSET))

# Combine 'Other' categories in factored variables 
test_clean <- test_clean |>
  mutate(
    NAME_TYPE_SUITE = case_when(
      NAME_TYPE_SUITE %in% c("", "Other_A", "Other_B", "Other") ~ "Other",
      # Combine blanks and 2 "other" categories into "Other" category
      TRUE ~ NAME_TYPE_SUITE
    ),
    # Keep all other values unchanged
    OCCUPATION_TYPE = case_when(OCCUPATION_TYPE == "" ~ "Other", # Replace blank values with "Other"
                                TRUE ~ OCCUPATION_TYPE),
    # Keep all other values unchanged
    HOUSETYPE_MODE = case_when(HOUSETYPE_MODE == "" ~ "other", # Replace blank values with "Other"
                               TRUE ~ HOUSETYPE_MODE))

# Impute DAYS_EMPLOYED with median
test_clean <- test_clean |>
  mutate(DAYS_EMPLOYED = ifelse(DAYS_EMPLOYED > 18250, median(DAYS_EMPLOYED), DAYS_EMPLOYED))

# Impute EXT_SOURCE_1 with 0 indicating no credit score
test_clean <- test_clean |>
  mutate(EXT_SOURCE_1 = ifelse(is.na(EXT_SOURCE_1), 0, EXT_SOURCE_1))

# Impute EXT_SOURCE_2 with 0 indicating no credit score
test_clean <- test_clean |>
  mutate(EXT_SOURCE_2 = ifelse(is.na(EXT_SOURCE_2), 0, EXT_SOURCE_2))

# Impute EXT_SOURCE_3 with 0 indicating no credit score
test_clean <- test_clean |>
  mutate(EXT_SOURCE_3 = ifelse(is.na(EXT_SOURCE_3), 0, EXT_SOURCE_3))

# Impute CNT_FAM_MEMBERS with the median
test_clean <- test_clean |>
  mutate(CNT_FAM_MEMBERS = ifelse(is.na(CNT_FAM_MEMBERS), median(CNT_FAM_MEMBERS, na.rm = TRUE), CNT_FAM_MEMBERS))

# Impute AMT_ANNUITY with the median
test_clean <- test_clean |>
  mutate(AMT_ANNUITY = ifelse(is.na(AMT_ANNUITY), median(AMT_ANNUITY, na.rm = TRUE), AMT_ANNUITY))

# Impute AMT_GOODS_PRICE with the median
test_clean <- test_clean |>
  mutate(AMT_GOODS_PRICE = ifelse(is.na(AMT_GOODS_PRICE), median(AMT_GOODS_PRICE, na.rm = TRUE), AMT_GOODS_PRICE))

# Impute DAYS_LAST_PHONE_CHANGE with the median
test_clean <- test_clean |>
  mutate(DAYS_LAST_PHONE_CHANGE = ifelse(is.na(DAYS_LAST_PHONE_CHANGE), median(DAYS_LAST_PHONE_CHANGE, na.rm = TRUE), DAYS_LAST_PHONE_CHANGE))

colSums(is.na(test_clean))

train_clean |>
  str()

# Save as RDS
saveRDS(test_clean, "application_test_cleaned.rds")

# Save as CSV for visual exploration
write.csv(test_clean, "application_test_cleaned.csv", row.names = FALSE)
```


```{r}
# Examine cleaned test and train data
str(train_clean)
str(test_clean)
```

